### ISSUE TITLE
US25: Como desarrollador del proyecto web, QUIERO desplegar el desarrollo web local en un hosting remoto PARA poner a disposición del público la versión final del proyecto.

### ISSUE THREAD

**Issue by Karen-Pigni** [DesarrollAR2024/proyecto-ispc-2024#62]
#TK25: Configurar y realizar el despliegue del desarrollo web local en un hosting remoto.

**Comment by PsicoDevil** [comment]
Se realizo la configuracion necesaria para deployar el sitio via FIREBASE - se correjiran los archivos  CSV o JSON. necesarios para vincular la bd - 

LINK AL SITIO GAMEMATE: https://gamematearg.web.app/

**Comment by PsicoDevil** [comment]
\proyecto-ispc-2024\AppWeb\Frontend\GameMate\.firebaserc

\proyecto-ispc-2024\AppWeb\Frontend\GameMate\firebase.json
